workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


stages:
  - build
  - deploy

build:
  stage: build
  image: python:3.10-bullseye
  before_script:
    - python3 -m pip install -U pip
    - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - pip3 install -r requirements.txt
  script:
    - mkdocs build
  artifacts:
    paths:
      - site/

deploy:
  stage: deploy
  only:
    - master
    - ci-test
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - 'command -v git >/dev/null || ( apt-get update -y && apt-get install git -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - git config --global user.email "ci@git.tsinghua.edu.cn"
    - git config --global user.name "GitLab CI"
  script:
    - cd site
    - git init && git remote add deploy git@meow.plus:physics-data/faq.git
    - git add . && git commit -m "Deploy"
    - GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push deploy master -f
